### ISSUE TITLE
shadeMS/daskms spectral window error

### ISSUE THREAD

**Issue by JonahDW** [IanHeywood/shadeMS#7]
I've attempted some simple plotting commands with the code, however I'm running into an issue apparently to do with the spectral windows. Trying to run the program with
`shadems --xaxis t --yaxis a J1833.ms`
 
Produces the following error:
```
  File "/homes/wagenveld/anaconda3/bin/shadems", line 8, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/homes/wagenveld/anaconda3/lib/python3.7/site-packages/ShadeMS/main.py", line 125, in main
    chan_freqs = sms.get_chan_freqs(myms)
  File "/homes/wagenveld/anaconda3/lib/python3.7/site-packages/ShadeMS/shadeMS.py", line 18, in get_chan_freqs
    myms+'::SPECTRAL_WINDOW', columns=['CHAN_FREQ'])
  File "/homes/wagenveld/anaconda3/lib/python3.7/site-packages/daskms/dask_ms.py", line 285, in xds_from_table
    **kwargs).datasets()
  File "/homes/wagenveld/anaconda3/lib/python3.7/site-packages/daskms/reads.py", line 276, in __init__
    raise ValueError("'%s' does not appear to be a CASA Table" % table)
ValueError: 'J1833.ms::SPECTRAL_WINDOW' does not appear to be a CASA Table
```

Any insights would be greatly appreciated. 
Cheers, Jonah

**Comment by o-smirnov** [comment]
Well that's odd. Can you check if ``J1833.ms/SPECTRAL_WINDOW`` is a valid table in your MS?

**Comment by JonahDW** [comment]
It has the structure a table ought to have as far as I can see, containing the table.dat, table.info, table.f0, table.f0i and table.lock files. 
Is there any way to check with CASA if it considers the table valid?

**Comment by o-smirnov** [comment]
Could you please try this in plain Python and report if there's any error messages:

```
from casacore.tables import table
tab = table("J1833.ms/SPECTRAL_WINDOW")
tab = table("J1833.ms::SPECTRAL_WINDOW")
```

**Comment by JonahDW** [comment]
Okay, turns out I was being a big idiot, all is resolved now, it was no issue with the program. Thanks for the help and quick responses, apologies for taking your time. 

Cheers

**Comment by IanHeywood** [comment]
Thanks @o-smirnov.

> Is there any way to check with CASA if it considers the table valid?

The CASA equivalent to Oleg's trick would be:

```
tb.open('J1833.ms/SPECTRAL_WINDOW')
```

then you could try e.g.

```
tb.browse()
```

Cheers.
