### ISSUE TITLE
Memory errors plotting with shadeMS

### ISSUE THREAD

**Issue by JonahDW** [IanHeywood/shadeMS#8]
Trying to plot a simple plot (amp vs uv) of an 34GB ms currently yields (perhaps unsurprisingly) a memory error from numpy. 

Is there any way to work around this in the current state of the program? I don't see any options to really select a subset of the data (besides the field and spw, but my dataset already only one of either) for plotting.

Thanks in advance.

**Comment by IanHeywood** [comment]
Hi Jonah. There's no on-the-fly averaging capability at present, sorry. It's probably not worth trying to implement such a thing until #3 is fixed, which will require a bit of a re-write of the main code, which just leaves the eternal problem of finding the time to do it.

Maybe give casaplotms a try, with time and frequency averaging enabled.

**Comment by IanHeywood** [comment]
@Mulan-94's `ragavi-vis` plotter might also work for you.

**Comment by JonahDW** [comment]
Hey Ian,

Thanks, I can appreciate the work that must be put in to get these things in order. For now, I'll mostly stick to plotms. I've also made some adjustments to your main code to make it plot a subset of channels (it's very ugly, but it works), so that my RAM just about makes it through the whole ordeal alive.

Cheers, Jonah

**Comment by o-smirnov** [comment]
@JonahDW try the latest please, it no longer loads the entire MS. Further tweaking is possible (since at the moment dask selects chunk sizes automatically)

**Comment by JonahDW** [comment]
Thanks @o-smirnov , that worked like a charm.
